### ISSUE TITLE
[IMPORTANTE] Formulario de Contato do site nao esta funcionando

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/brasa-2018-theme#8]
Pessoal, fiz um teste basico pra ver se o contato pelo site esta funcionando e infelizmente nao esta:

1 - Quando clico para enviar a mensagem, nao existe nenhuma mensagem de feedback falando que foi enviado com sucesso;
2 - O e-mail nao foi enviado para o aoseudispor@

![image](https://user-images.githubusercontent.com/5949986/36357291-8e1893c4-14c1-11e8-93a6-3a6e8eea2547.png)

**Comment by LuwkasLima** [comment]
Pessoal, precisamos resolver isso com certa urgencia. Tamo sem possibilidade de receber contato pelo site....

**Comment by diegorojas** [comment]
Resolvido mano! usando o Easy WP SMTP.
